//
// Copyright (C) 2017 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.4
// source: frameworks/base/core/proto/android/os/looper.proto

package os

import (
	_ "github.com/zopieux/dumpsys-exporter/proto/android/frameworks/base/core/proto/android"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LooperProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// the thread name, usually set by developers.
	ThreadName *string            `protobuf:"bytes,1,opt,name=thread_name,json=threadName" json:"thread_name,omitempty"`
	ThreadId   *int64             `protobuf:"varint,2,opt,name=thread_id,json=threadId" json:"thread_id,omitempty"`
	Queue      *MessageQueueProto `protobuf:"bytes,3,opt,name=queue" json:"queue,omitempty"`
}

func (x *LooperProto) Reset() {
	*x = LooperProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frameworks_base_core_proto_android_os_looper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LooperProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LooperProto) ProtoMessage() {}

func (x *LooperProto) ProtoReflect() protoreflect.Message {
	mi := &file_frameworks_base_core_proto_android_os_looper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LooperProto.ProtoReflect.Descriptor instead.
func (*LooperProto) Descriptor() ([]byte, []int) {
	return file_frameworks_base_core_proto_android_os_looper_proto_rawDescGZIP(), []int{0}
}

func (x *LooperProto) GetThreadName() string {
	if x != nil && x.ThreadName != nil {
		return *x.ThreadName
	}
	return ""
}

func (x *LooperProto) GetThreadId() int64 {
	if x != nil && x.ThreadId != nil {
		return *x.ThreadId
	}
	return 0
}

func (x *LooperProto) GetQueue() *MessageQueueProto {
	if x != nil {
		return x.Queue
	}
	return nil
}

var File_frameworks_base_core_proto_android_os_looper_proto protoreflect.FileDescriptor

var file_frameworks_base_core_proto_android_os_looper_proto_rawDesc = []byte{
	0x0a, 0x32, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2f, 0x62, 0x61, 0x73,
	0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6e, 0x64,
	0x72, 0x6f, 0x69, 0x64, 0x2f, 0x6f, 0x73, 0x2f, 0x6c, 0x6f, 0x6f, 0x70, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x2e, 0x6f, 0x73,
	0x1a, 0x38, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2f, 0x62, 0x61, 0x73,
	0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6e, 0x64,
	0x72, 0x6f, 0x69, 0x64, 0x2f, 0x6f, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x71,
	0x75, 0x65, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x30, 0x66, 0x72, 0x61, 0x6d,
	0x65, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x2f, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8b, 0x01, 0x0a,
	0x0b, 0x4c, 0x6f, 0x6f, 0x70, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1f, 0x0a, 0x0b,
	0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x05, 0x71, 0x75,
	0x65, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x6e, 0x64, 0x72,
	0x6f, 0x69, 0x64, 0x2e, 0x6f, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x51, 0x75,
	0x65, 0x75, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x05, 0x71, 0x75, 0x65, 0x75, 0x65, 0x3a,
	0x09, 0x9a, 0x9f, 0xd5, 0x87, 0x03, 0x03, 0x08, 0xc8, 0x01, 0x42, 0x02, 0x50, 0x01,
}

var (
	file_frameworks_base_core_proto_android_os_looper_proto_rawDescOnce sync.Once
	file_frameworks_base_core_proto_android_os_looper_proto_rawDescData = file_frameworks_base_core_proto_android_os_looper_proto_rawDesc
)

func file_frameworks_base_core_proto_android_os_looper_proto_rawDescGZIP() []byte {
	file_frameworks_base_core_proto_android_os_looper_proto_rawDescOnce.Do(func() {
		file_frameworks_base_core_proto_android_os_looper_proto_rawDescData = protoimpl.X.CompressGZIP(file_frameworks_base_core_proto_android_os_looper_proto_rawDescData)
	})
	return file_frameworks_base_core_proto_android_os_looper_proto_rawDescData
}

var file_frameworks_base_core_proto_android_os_looper_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_frameworks_base_core_proto_android_os_looper_proto_goTypes = []any{
	(*LooperProto)(nil),       // 0: android.os.LooperProto
	(*MessageQueueProto)(nil), // 1: android.os.MessageQueueProto
}
var file_frameworks_base_core_proto_android_os_looper_proto_depIdxs = []int32{
	1, // 0: android.os.LooperProto.queue:type_name -> android.os.MessageQueueProto
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_frameworks_base_core_proto_android_os_looper_proto_init() }
func file_frameworks_base_core_proto_android_os_looper_proto_init() {
	if File_frameworks_base_core_proto_android_os_looper_proto != nil {
		return
	}
	file_frameworks_base_core_proto_android_os_messagequeue_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_frameworks_base_core_proto_android_os_looper_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*LooperProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_frameworks_base_core_proto_android_os_looper_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_frameworks_base_core_proto_android_os_looper_proto_goTypes,
		DependencyIndexes: file_frameworks_base_core_proto_android_os_looper_proto_depIdxs,
		MessageInfos:      file_frameworks_base_core_proto_android_os_looper_proto_msgTypes,
	}.Build()
	File_frameworks_base_core_proto_android_os_looper_proto = out.File
	file_frameworks_base_core_proto_android_os_looper_proto_rawDesc = nil
	file_frameworks_base_core_proto_android_os_looper_proto_goTypes = nil
	file_frameworks_base_core_proto_android_os_looper_proto_depIdxs = nil
}
