//
// Copyright (C) 2017 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.4
// source: frameworks/base/core/proto/android/os/message.proto

package os

import (
	_ "github.com/zopieux/dumpsys-exporter/proto/android/frameworks/base/core/proto/android"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Targeted delivery time of the message.
	When *int64 `protobuf:"varint,1,opt,name=when" json:"when,omitempty"`
	// Name of callback class.
	Callback *string `protobuf:"bytes,2,opt,name=callback" json:"callback,omitempty"`
	// App-defined message code so that the recipient can identify what this
	// message is about.
	What *int32 `protobuf:"varint,3,opt,name=what" json:"what,omitempty"`
	// Lower-cost alternative to using setData() if the app only needs to store a few integer values.
	Arg1 *int32 `protobuf:"varint,4,opt,name=arg1" json:"arg1,omitempty"`
	// Lower-cost alternative to using setData() if the app only needs to store a few integer values.
	Arg2 *int32 `protobuf:"varint,5,opt,name=arg2" json:"arg2,omitempty"`
	// String representation of an arbitrary object to send to the Handler.  When
	// using android.os.Messenger to send the message across processes, this will
	// only be populated if it contains a Parcelable of a framework class (not one
	// implemented by the application).
	Obj *string `protobuf:"bytes,6,opt,name=obj" json:"obj,omitempty"`
	// Name of target class.
	Target  *string `protobuf:"bytes,7,opt,name=target" json:"target,omitempty"`
	Barrier *int32  `protobuf:"varint,8,opt,name=barrier" json:"barrier,omitempty"`
}

func (x *MessageProto) Reset() {
	*x = MessageProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frameworks_base_core_proto_android_os_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageProto) ProtoMessage() {}

func (x *MessageProto) ProtoReflect() protoreflect.Message {
	mi := &file_frameworks_base_core_proto_android_os_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageProto.ProtoReflect.Descriptor instead.
func (*MessageProto) Descriptor() ([]byte, []int) {
	return file_frameworks_base_core_proto_android_os_message_proto_rawDescGZIP(), []int{0}
}

func (x *MessageProto) GetWhen() int64 {
	if x != nil && x.When != nil {
		return *x.When
	}
	return 0
}

func (x *MessageProto) GetCallback() string {
	if x != nil && x.Callback != nil {
		return *x.Callback
	}
	return ""
}

func (x *MessageProto) GetWhat() int32 {
	if x != nil && x.What != nil {
		return *x.What
	}
	return 0
}

func (x *MessageProto) GetArg1() int32 {
	if x != nil && x.Arg1 != nil {
		return *x.Arg1
	}
	return 0
}

func (x *MessageProto) GetArg2() int32 {
	if x != nil && x.Arg2 != nil {
		return *x.Arg2
	}
	return 0
}

func (x *MessageProto) GetObj() string {
	if x != nil && x.Obj != nil {
		return *x.Obj
	}
	return ""
}

func (x *MessageProto) GetTarget() string {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return ""
}

func (x *MessageProto) GetBarrier() int32 {
	if x != nil && x.Barrier != nil {
		return *x.Barrier
	}
	return 0
}

var File_frameworks_base_core_proto_android_os_message_proto protoreflect.FileDescriptor

var file_frameworks_base_core_proto_android_os_message_proto_rawDesc = []byte{
	0x0a, 0x33, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2f, 0x62, 0x61, 0x73,
	0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6e, 0x64,
	0x72, 0x6f, 0x69, 0x64, 0x2f, 0x6f, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x2e, 0x6f,
	0x73, 0x1a, 0x30, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2f, 0x62, 0x61,
	0x73, 0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6e,
	0x64, 0x72, 0x6f, 0x69, 0x64, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xd3, 0x01, 0x0a, 0x0c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x68, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x77, 0x68, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c,
	0x62, 0x61, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c,
	0x62, 0x61, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x68, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x77, 0x68, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x31,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x61, 0x72, 0x67, 0x31, 0x12, 0x12, 0x0a, 0x04,
	0x61, 0x72, 0x67, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x61, 0x72, 0x67, 0x32,
	0x12, 0x1a, 0x0a, 0x03, 0x6f, 0x62, 0x6a, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x42, 0x08, 0x9a,
	0x9f, 0xd5, 0x87, 0x03, 0x02, 0x08, 0x64, 0x52, 0x03, 0x6f, 0x62, 0x6a, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x62, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x3a, 0x09,
	0x9a, 0x9f, 0xd5, 0x87, 0x03, 0x03, 0x08, 0xc8, 0x01, 0x42, 0x02, 0x50, 0x01,
}

var (
	file_frameworks_base_core_proto_android_os_message_proto_rawDescOnce sync.Once
	file_frameworks_base_core_proto_android_os_message_proto_rawDescData = file_frameworks_base_core_proto_android_os_message_proto_rawDesc
)

func file_frameworks_base_core_proto_android_os_message_proto_rawDescGZIP() []byte {
	file_frameworks_base_core_proto_android_os_message_proto_rawDescOnce.Do(func() {
		file_frameworks_base_core_proto_android_os_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_frameworks_base_core_proto_android_os_message_proto_rawDescData)
	})
	return file_frameworks_base_core_proto_android_os_message_proto_rawDescData
}

var file_frameworks_base_core_proto_android_os_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_frameworks_base_core_proto_android_os_message_proto_goTypes = []any{
	(*MessageProto)(nil), // 0: android.os.MessageProto
}
var file_frameworks_base_core_proto_android_os_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_frameworks_base_core_proto_android_os_message_proto_init() }
func file_frameworks_base_core_proto_android_os_message_proto_init() {
	if File_frameworks_base_core_proto_android_os_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_frameworks_base_core_proto_android_os_message_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MessageProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_frameworks_base_core_proto_android_os_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_frameworks_base_core_proto_android_os_message_proto_goTypes,
		DependencyIndexes: file_frameworks_base_core_proto_android_os_message_proto_depIdxs,
		MessageInfos:      file_frameworks_base_core_proto_android_os_message_proto_msgTypes,
	}.Build()
	File_frameworks_base_core_proto_android_os_message_proto = out.File
	file_frameworks_base_core_proto_android_os_message_proto_rawDesc = nil
	file_frameworks_base_core_proto_android_os_message_proto_goTypes = nil
	file_frameworks_base_core_proto_android_os_message_proto_depIdxs = nil
}
