//
// Copyright (C) 2017 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.4
// source: frameworks/base/core/proto/android/os/patternmatcher.proto

package os

import (
	_ "github.com/zopieux/dumpsys-exporter/proto/android/frameworks/base/core/proto/android"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PatternMatcherProto_Type int32

const (
	PatternMatcherProto_TYPE_LITERAL       PatternMatcherProto_Type = 0
	PatternMatcherProto_TYPE_PREFIX        PatternMatcherProto_Type = 1
	PatternMatcherProto_TYPE_SIMPLE_GLOB   PatternMatcherProto_Type = 2
	PatternMatcherProto_TYPE_ADVANCED_GLOB PatternMatcherProto_Type = 3
)

// Enum value maps for PatternMatcherProto_Type.
var (
	PatternMatcherProto_Type_name = map[int32]string{
		0: "TYPE_LITERAL",
		1: "TYPE_PREFIX",
		2: "TYPE_SIMPLE_GLOB",
		3: "TYPE_ADVANCED_GLOB",
	}
	PatternMatcherProto_Type_value = map[string]int32{
		"TYPE_LITERAL":       0,
		"TYPE_PREFIX":        1,
		"TYPE_SIMPLE_GLOB":   2,
		"TYPE_ADVANCED_GLOB": 3,
	}
)

func (x PatternMatcherProto_Type) Enum() *PatternMatcherProto_Type {
	p := new(PatternMatcherProto_Type)
	*p = x
	return p
}

func (x PatternMatcherProto_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PatternMatcherProto_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_frameworks_base_core_proto_android_os_patternmatcher_proto_enumTypes[0].Descriptor()
}

func (PatternMatcherProto_Type) Type() protoreflect.EnumType {
	return &file_frameworks_base_core_proto_android_os_patternmatcher_proto_enumTypes[0]
}

func (x PatternMatcherProto_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PatternMatcherProto_Type) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PatternMatcherProto_Type(num)
	return nil
}

// Deprecated: Use PatternMatcherProto_Type.Descriptor instead.
func (PatternMatcherProto_Type) EnumDescriptor() ([]byte, []int) {
	return file_frameworks_base_core_proto_android_os_patternmatcher_proto_rawDescGZIP(), []int{0, 0}
}

type PatternMatcherProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pattern *string                   `protobuf:"bytes,1,opt,name=pattern" json:"pattern,omitempty"`
	Type    *PatternMatcherProto_Type `protobuf:"varint,2,opt,name=type,enum=android.os.PatternMatcherProto_Type" json:"type,omitempty"`
}

func (x *PatternMatcherProto) Reset() {
	*x = PatternMatcherProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frameworks_base_core_proto_android_os_patternmatcher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatternMatcherProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatternMatcherProto) ProtoMessage() {}

func (x *PatternMatcherProto) ProtoReflect() protoreflect.Message {
	mi := &file_frameworks_base_core_proto_android_os_patternmatcher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatternMatcherProto.ProtoReflect.Descriptor instead.
func (*PatternMatcherProto) Descriptor() ([]byte, []int) {
	return file_frameworks_base_core_proto_android_os_patternmatcher_proto_rawDescGZIP(), []int{0}
}

func (x *PatternMatcherProto) GetPattern() string {
	if x != nil && x.Pattern != nil {
		return *x.Pattern
	}
	return ""
}

func (x *PatternMatcherProto) GetType() PatternMatcherProto_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return PatternMatcherProto_TYPE_LITERAL
}

var File_frameworks_base_core_proto_android_os_patternmatcher_proto protoreflect.FileDescriptor

var file_frameworks_base_core_proto_android_os_patternmatcher_proto_rawDesc = []byte{
	0x0a, 0x3a, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2f, 0x62, 0x61, 0x73,
	0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6e, 0x64,
	0x72, 0x6f, 0x69, 0x64, 0x2f, 0x6f, 0x73, 0x2f, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x6e,
	0x64, 0x72, 0x6f, 0x69, 0x64, 0x2e, 0x6f, 0x73, 0x1a, 0x30, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x77,
	0x6f, 0x72, 0x6b, 0x73, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x2f, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x63, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcc, 0x01, 0x0a, 0x13, 0x50,
	0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x12, 0x38, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x61, 0x6e, 0x64,
	0x72, 0x6f, 0x69, 0x64, 0x2e, 0x6f, 0x73, 0x2e, 0x50, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x57, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10,
	0x0a, 0x0c, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4c, 0x49, 0x54, 0x45, 0x52, 0x41, 0x4c, 0x10, 0x00,
	0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x52, 0x45, 0x46, 0x49, 0x58, 0x10,
	0x01, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x49, 0x4d, 0x50, 0x4c, 0x45,
	0x5f, 0x47, 0x4c, 0x4f, 0x42, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x41, 0x44, 0x56, 0x41, 0x4e, 0x43, 0x45, 0x44, 0x5f, 0x47, 0x4c, 0x4f, 0x42, 0x10, 0x03, 0x3a,
	0x08, 0x9a, 0x9f, 0xd5, 0x87, 0x03, 0x02, 0x08, 0x64, 0x42, 0x02, 0x50, 0x01,
}

var (
	file_frameworks_base_core_proto_android_os_patternmatcher_proto_rawDescOnce sync.Once
	file_frameworks_base_core_proto_android_os_patternmatcher_proto_rawDescData = file_frameworks_base_core_proto_android_os_patternmatcher_proto_rawDesc
)

func file_frameworks_base_core_proto_android_os_patternmatcher_proto_rawDescGZIP() []byte {
	file_frameworks_base_core_proto_android_os_patternmatcher_proto_rawDescOnce.Do(func() {
		file_frameworks_base_core_proto_android_os_patternmatcher_proto_rawDescData = protoimpl.X.CompressGZIP(file_frameworks_base_core_proto_android_os_patternmatcher_proto_rawDescData)
	})
	return file_frameworks_base_core_proto_android_os_patternmatcher_proto_rawDescData
}

var file_frameworks_base_core_proto_android_os_patternmatcher_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_frameworks_base_core_proto_android_os_patternmatcher_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_frameworks_base_core_proto_android_os_patternmatcher_proto_goTypes = []any{
	(PatternMatcherProto_Type)(0), // 0: android.os.PatternMatcherProto.Type
	(*PatternMatcherProto)(nil),   // 1: android.os.PatternMatcherProto
}
var file_frameworks_base_core_proto_android_os_patternmatcher_proto_depIdxs = []int32{
	0, // 0: android.os.PatternMatcherProto.type:type_name -> android.os.PatternMatcherProto.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_frameworks_base_core_proto_android_os_patternmatcher_proto_init() }
func file_frameworks_base_core_proto_android_os_patternmatcher_proto_init() {
	if File_frameworks_base_core_proto_android_os_patternmatcher_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_frameworks_base_core_proto_android_os_patternmatcher_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PatternMatcherProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_frameworks_base_core_proto_android_os_patternmatcher_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_frameworks_base_core_proto_android_os_patternmatcher_proto_goTypes,
		DependencyIndexes: file_frameworks_base_core_proto_android_os_patternmatcher_proto_depIdxs,
		EnumInfos:         file_frameworks_base_core_proto_android_os_patternmatcher_proto_enumTypes,
		MessageInfos:      file_frameworks_base_core_proto_android_os_patternmatcher_proto_msgTypes,
	}.Build()
	File_frameworks_base_core_proto_android_os_patternmatcher_proto = out.File
	file_frameworks_base_core_proto_android_os_patternmatcher_proto_rawDesc = nil
	file_frameworks_base_core_proto_android_os_patternmatcher_proto_goTypes = nil
	file_frameworks_base_core_proto_android_os_patternmatcher_proto_depIdxs = nil
}
