//
// Copyright (C) 2016 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.4
// source: frameworks/base/core/proto/android/privacy.proto

package android

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Destination int32

const (
	// Fields or messages annotated with DEST_LOCAL must never be
	// extracted from the device automatically. They can be accessed
	// by tools on the developer's workstation or test lab devices.
	Destination_DEST_LOCAL Destination = 0
	// Fields or messages annotated with DEST_EXPLICIT can be sent
	// off the device with an explicit user action.
	Destination_DEST_EXPLICIT Destination = 100
	// Fields or messages annotated with DEST_AUTOMATIC can be sent by
	// automatic means, without per-sending user consent. The user
	// still must have previously accepted a consent to share this
	// information.
	Destination_DEST_AUTOMATIC Destination = 200
	// This is the default value, which could be overridden by other values.
	// The reason to pick 255 is it fits into one byte. UNSET fields are treated
	// as EXPLICIT.
	Destination_DEST_UNSET Destination = 255
)

// Enum value maps for Destination.
var (
	Destination_name = map[int32]string{
		0:   "DEST_LOCAL",
		100: "DEST_EXPLICIT",
		200: "DEST_AUTOMATIC",
		255: "DEST_UNSET",
	}
	Destination_value = map[string]int32{
		"DEST_LOCAL":     0,
		"DEST_EXPLICIT":  100,
		"DEST_AUTOMATIC": 200,
		"DEST_UNSET":     255,
	}
)

func (x Destination) Enum() *Destination {
	p := new(Destination)
	*p = x
	return p
}

func (x Destination) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Destination) Descriptor() protoreflect.EnumDescriptor {
	return file_frameworks_base_core_proto_android_privacy_proto_enumTypes[0].Descriptor()
}

func (Destination) Type() protoreflect.EnumType {
	return &file_frameworks_base_core_proto_android_privacy_proto_enumTypes[0]
}

func (x Destination) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Destination) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Destination(num)
	return nil
}

// Deprecated: Use Destination.Descriptor instead.
func (Destination) EnumDescriptor() ([]byte, []int) {
	return file_frameworks_base_core_proto_android_privacy_proto_rawDescGZIP(), []int{0}
}

type PrivacyFlags struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dest *Destination `protobuf:"varint,1,opt,name=dest,enum=android.Destination,def=255" json:"dest,omitempty"`
	// regex to filter pii sensitive info from a string field type.
	Patterns []string `protobuf:"bytes,2,rep,name=patterns" json:"patterns,omitempty"`
}

// Default values for PrivacyFlags fields.
const (
	Default_PrivacyFlags_Dest = Destination_DEST_UNSET
)

func (x *PrivacyFlags) Reset() {
	*x = PrivacyFlags{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frameworks_base_core_proto_android_privacy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrivacyFlags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivacyFlags) ProtoMessage() {}

func (x *PrivacyFlags) ProtoReflect() protoreflect.Message {
	mi := &file_frameworks_base_core_proto_android_privacy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivacyFlags.ProtoReflect.Descriptor instead.
func (*PrivacyFlags) Descriptor() ([]byte, []int) {
	return file_frameworks_base_core_proto_android_privacy_proto_rawDescGZIP(), []int{0}
}

func (x *PrivacyFlags) GetDest() Destination {
	if x != nil && x.Dest != nil {
		return *x.Dest
	}
	return Default_PrivacyFlags_Dest
}

func (x *PrivacyFlags) GetPatterns() []string {
	if x != nil {
		return x.Patterns
	}
	return nil
}

var file_frameworks_base_core_proto_android_privacy_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*PrivacyFlags)(nil),
		Field:         102672883,
		Name:          "android.privacy",
		Tag:           "bytes,102672883,opt,name=privacy",
		Filename:      "frameworks/base/core/proto/android/privacy.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*PrivacyFlags)(nil),
		Field:         102672883,
		Name:          "android.msg_privacy",
		Tag:           "bytes,102672883,opt,name=msg_privacy",
		Filename:      "frameworks/base/core/proto/android/privacy.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// Flags used to annotate a field with right privacy level.
	//
	// optional android.PrivacyFlags privacy = 102672883;
	E_Privacy = &file_frameworks_base_core_proto_android_privacy_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// Flags used to annotate a message which all its unset primitive fields inhert this tag.
	//
	// optional android.PrivacyFlags msg_privacy = 102672883;
	E_MsgPrivacy = &file_frameworks_base_core_proto_android_privacy_proto_extTypes[1]
)

var File_frameworks_base_core_proto_android_privacy_proto protoreflect.FileDescriptor

var file_frameworks_base_core_proto_android_privacy_proto_rawDesc = []byte{
	0x0a, 0x30, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2f, 0x62, 0x61, 0x73,
	0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6e, 0x64,
	0x72, 0x6f, 0x69, 0x64, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x1a, 0x20, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x60, 0x0a,
	0x0c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x12, 0x34, 0x0a,
	0x04, 0x64, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x61, 0x6e,
	0x64, 0x72, 0x6f, 0x69, 0x64, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x3a, 0x0a, 0x44, 0x45, 0x53, 0x54, 0x5f, 0x55, 0x4e, 0x53, 0x45, 0x54, 0x52, 0x04, 0x64,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x73, 0x2a,
	0x56, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e,
	0x0a, 0x0a, 0x44, 0x45, 0x53, 0x54, 0x5f, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x11,
	0x0a, 0x0d, 0x44, 0x45, 0x53, 0x54, 0x5f, 0x45, 0x58, 0x50, 0x4c, 0x49, 0x43, 0x49, 0x54, 0x10,
	0x64, 0x12, 0x13, 0x0a, 0x0e, 0x44, 0x45, 0x53, 0x54, 0x5f, 0x41, 0x55, 0x54, 0x4f, 0x4d, 0x41,
	0x54, 0x49, 0x43, 0x10, 0xc8, 0x01, 0x12, 0x0f, 0x0a, 0x0a, 0x44, 0x45, 0x53, 0x54, 0x5f, 0x55,
	0x4e, 0x53, 0x45, 0x54, 0x10, 0xff, 0x01, 0x3a, 0x51, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x63, 0x79, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0xf3, 0xd3, 0xfa, 0x30, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x6e, 0x64,
	0x72, 0x6f, 0x69, 0x64, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x46, 0x6c, 0x61, 0x67,
	0x73, 0x52, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x3a, 0x5a, 0x0a, 0x0b, 0x6d, 0x73,
	0x67, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xf3, 0xd3, 0xfa, 0x30, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x2e, 0x50, 0x72,
	0x69, 0x76, 0x61, 0x63, 0x79, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x52, 0x0a, 0x6d, 0x73, 0x67, 0x50,
	0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x42, 0x18, 0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e,
	0x64, 0x72, 0x6f, 0x69, 0x64, 0x2e, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x50, 0x01,
}

var (
	file_frameworks_base_core_proto_android_privacy_proto_rawDescOnce sync.Once
	file_frameworks_base_core_proto_android_privacy_proto_rawDescData = file_frameworks_base_core_proto_android_privacy_proto_rawDesc
)

func file_frameworks_base_core_proto_android_privacy_proto_rawDescGZIP() []byte {
	file_frameworks_base_core_proto_android_privacy_proto_rawDescOnce.Do(func() {
		file_frameworks_base_core_proto_android_privacy_proto_rawDescData = protoimpl.X.CompressGZIP(file_frameworks_base_core_proto_android_privacy_proto_rawDescData)
	})
	return file_frameworks_base_core_proto_android_privacy_proto_rawDescData
}

var file_frameworks_base_core_proto_android_privacy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_frameworks_base_core_proto_android_privacy_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_frameworks_base_core_proto_android_privacy_proto_goTypes = []any{
	(Destination)(0),                    // 0: android.Destination
	(*PrivacyFlags)(nil),                // 1: android.PrivacyFlags
	(*descriptorpb.FieldOptions)(nil),   // 2: google.protobuf.FieldOptions
	(*descriptorpb.MessageOptions)(nil), // 3: google.protobuf.MessageOptions
}
var file_frameworks_base_core_proto_android_privacy_proto_depIdxs = []int32{
	0, // 0: android.PrivacyFlags.dest:type_name -> android.Destination
	2, // 1: android.privacy:extendee -> google.protobuf.FieldOptions
	3, // 2: android.msg_privacy:extendee -> google.protobuf.MessageOptions
	1, // 3: android.privacy:type_name -> android.PrivacyFlags
	1, // 4: android.msg_privacy:type_name -> android.PrivacyFlags
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	3, // [3:5] is the sub-list for extension type_name
	1, // [1:3] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_frameworks_base_core_proto_android_privacy_proto_init() }
func file_frameworks_base_core_proto_android_privacy_proto_init() {
	if File_frameworks_base_core_proto_android_privacy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_frameworks_base_core_proto_android_privacy_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PrivacyFlags); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_frameworks_base_core_proto_android_privacy_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_frameworks_base_core_proto_android_privacy_proto_goTypes,
		DependencyIndexes: file_frameworks_base_core_proto_android_privacy_proto_depIdxs,
		EnumInfos:         file_frameworks_base_core_proto_android_privacy_proto_enumTypes,
		MessageInfos:      file_frameworks_base_core_proto_android_privacy_proto_msgTypes,
		ExtensionInfos:    file_frameworks_base_core_proto_android_privacy_proto_extTypes,
	}.Build()
	File_frameworks_base_core_proto_android_privacy_proto = out.File
	file_frameworks_base_core_proto_android_privacy_proto_rawDesc = nil
	file_frameworks_base_core_proto_android_privacy_proto_goTypes = nil
	file_frameworks_base_core_proto_android_privacy_proto_depIdxs = nil
}
