//
// Copyright (C) 2017 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.4
// source: frameworks/base/core/proto/android/providers/settings/common.proto

package settings

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SettingProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID of the setting
	Id *string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// Name of the setting
	Name *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// Package name of the setting
	Pkg *string `protobuf:"bytes,3,opt,name=pkg" json:"pkg,omitempty"`
	// Value of this setting
	Value *string `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
	// Default value of this setting
	DefaultValue *string `protobuf:"bytes,5,opt,name=default_value,json=defaultValue" json:"default_value,omitempty"`
	// Whether the default is set by the system
	DefaultFromSystem *bool `protobuf:"varint,6,opt,name=default_from_system,json=defaultFromSystem" json:"default_from_system,omitempty"`
}

func (x *SettingProto) Reset() {
	*x = SettingProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frameworks_base_core_proto_android_providers_settings_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SettingProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingProto) ProtoMessage() {}

func (x *SettingProto) ProtoReflect() protoreflect.Message {
	mi := &file_frameworks_base_core_proto_android_providers_settings_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingProto.ProtoReflect.Descriptor instead.
func (*SettingProto) Descriptor() ([]byte, []int) {
	return file_frameworks_base_core_proto_android_providers_settings_common_proto_rawDescGZIP(), []int{0}
}

func (x *SettingProto) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *SettingProto) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *SettingProto) GetPkg() string {
	if x != nil && x.Pkg != nil {
		return *x.Pkg
	}
	return ""
}

func (x *SettingProto) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *SettingProto) GetDefaultValue() string {
	if x != nil && x.DefaultValue != nil {
		return *x.DefaultValue
	}
	return ""
}

func (x *SettingProto) GetDefaultFromSystem() bool {
	if x != nil && x.DefaultFromSystem != nil {
		return *x.DefaultFromSystem
	}
	return false
}

type SettingsOperationProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// When the operation happened
	Timestamp *int64 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	// Type of the operation
	Operation *string `protobuf:"bytes,2,opt,name=operation" json:"operation,omitempty"`
	// Name of the setting that was affected (optional)
	Setting *string `protobuf:"bytes,3,opt,name=setting" json:"setting,omitempty"`
}

func (x *SettingsOperationProto) Reset() {
	*x = SettingsOperationProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frameworks_base_core_proto_android_providers_settings_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SettingsOperationProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsOperationProto) ProtoMessage() {}

func (x *SettingsOperationProto) ProtoReflect() protoreflect.Message {
	mi := &file_frameworks_base_core_proto_android_providers_settings_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsOperationProto.ProtoReflect.Descriptor instead.
func (*SettingsOperationProto) Descriptor() ([]byte, []int) {
	return file_frameworks_base_core_proto_android_providers_settings_common_proto_rawDescGZIP(), []int{1}
}

func (x *SettingsOperationProto) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *SettingsOperationProto) GetOperation() string {
	if x != nil && x.Operation != nil {
		return *x.Operation
	}
	return ""
}

func (x *SettingsOperationProto) GetSetting() string {
	if x != nil && x.Setting != nil {
		return *x.Setting
	}
	return ""
}

var File_frameworks_base_core_proto_android_providers_settings_common_proto protoreflect.FileDescriptor

var file_frameworks_base_core_proto_android_providers_settings_common_proto_rawDesc = []byte{
	0x0a, 0x42, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2f, 0x62, 0x61, 0x73,
	0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6e, 0x64,
	0x72, 0x6f, 0x69, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x73,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x22, 0xaf, 0x01, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6b, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x70, 0x6b, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a,
	0x0d, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x66, 0x72,
	0x6f, 0x6d, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x11, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x22, 0x6e, 0x0a, 0x16, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x42, 0x02, 0x50, 0x01,
}

var (
	file_frameworks_base_core_proto_android_providers_settings_common_proto_rawDescOnce sync.Once
	file_frameworks_base_core_proto_android_providers_settings_common_proto_rawDescData = file_frameworks_base_core_proto_android_providers_settings_common_proto_rawDesc
)

func file_frameworks_base_core_proto_android_providers_settings_common_proto_rawDescGZIP() []byte {
	file_frameworks_base_core_proto_android_providers_settings_common_proto_rawDescOnce.Do(func() {
		file_frameworks_base_core_proto_android_providers_settings_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_frameworks_base_core_proto_android_providers_settings_common_proto_rawDescData)
	})
	return file_frameworks_base_core_proto_android_providers_settings_common_proto_rawDescData
}

var file_frameworks_base_core_proto_android_providers_settings_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_frameworks_base_core_proto_android_providers_settings_common_proto_goTypes = []any{
	(*SettingProto)(nil),           // 0: android.providers.settings.SettingProto
	(*SettingsOperationProto)(nil), // 1: android.providers.settings.SettingsOperationProto
}
var file_frameworks_base_core_proto_android_providers_settings_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_frameworks_base_core_proto_android_providers_settings_common_proto_init() }
func file_frameworks_base_core_proto_android_providers_settings_common_proto_init() {
	if File_frameworks_base_core_proto_android_providers_settings_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_frameworks_base_core_proto_android_providers_settings_common_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SettingProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frameworks_base_core_proto_android_providers_settings_common_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SettingsOperationProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_frameworks_base_core_proto_android_providers_settings_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_frameworks_base_core_proto_android_providers_settings_common_proto_goTypes,
		DependencyIndexes: file_frameworks_base_core_proto_android_providers_settings_common_proto_depIdxs,
		MessageInfos:      file_frameworks_base_core_proto_android_providers_settings_common_proto_msgTypes,
	}.Build()
	File_frameworks_base_core_proto_android_providers_settings_common_proto = out.File
	file_frameworks_base_core_proto_android_providers_settings_common_proto_rawDesc = nil
	file_frameworks_base_core_proto_android_providers_settings_common_proto_goTypes = nil
	file_frameworks_base_core_proto_android_providers_settings_common_proto_depIdxs = nil
}
