//
// Copyright (C) 2023 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.4
// source: frameworks/base/core/proto/android/providers/settings/generation.proto

package settings

import (
	_ "github.com/zopieux/dumpsys-exporter/proto/android/frameworks/base/core/proto/android"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerationRegistryProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumBackingStores    *int32               `protobuf:"varint,1,opt,name=num_backing_stores,json=numBackingStores" json:"num_backing_stores,omitempty"`
	NumMaxBackingStores *int32               `protobuf:"varint,2,opt,name=num_max_backing_stores,json=numMaxBackingStores" json:"num_max_backing_stores,omitempty"`
	BackingStores       []*BackingStoreProto `protobuf:"bytes,3,rep,name=backing_stores,json=backingStores" json:"backing_stores,omitempty"`
}

func (x *GenerationRegistryProto) Reset() {
	*x = GenerationRegistryProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frameworks_base_core_proto_android_providers_settings_generation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerationRegistryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerationRegistryProto) ProtoMessage() {}

func (x *GenerationRegistryProto) ProtoReflect() protoreflect.Message {
	mi := &file_frameworks_base_core_proto_android_providers_settings_generation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerationRegistryProto.ProtoReflect.Descriptor instead.
func (*GenerationRegistryProto) Descriptor() ([]byte, []int) {
	return file_frameworks_base_core_proto_android_providers_settings_generation_proto_rawDescGZIP(), []int{0}
}

func (x *GenerationRegistryProto) GetNumBackingStores() int32 {
	if x != nil && x.NumBackingStores != nil {
		return *x.NumBackingStores
	}
	return 0
}

func (x *GenerationRegistryProto) GetNumMaxBackingStores() int32 {
	if x != nil && x.NumMaxBackingStores != nil {
		return *x.NumMaxBackingStores
	}
	return 0
}

func (x *GenerationRegistryProto) GetBackingStores() []*BackingStoreProto {
	if x != nil {
		return x.BackingStores
	}
	return nil
}

type BackingStoreProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key              *int32             `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	BackingStoreSize *int32             `protobuf:"varint,2,opt,name=backing_store_size,json=backingStoreSize" json:"backing_store_size,omitempty"`
	NumCachedEntries *int32             `protobuf:"varint,3,opt,name=num_cached_entries,json=numCachedEntries" json:"num_cached_entries,omitempty"`
	CacheEntries     []*CacheEntryProto `protobuf:"bytes,4,rep,name=cache_entries,json=cacheEntries" json:"cache_entries,omitempty"`
}

func (x *BackingStoreProto) Reset() {
	*x = BackingStoreProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frameworks_base_core_proto_android_providers_settings_generation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackingStoreProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackingStoreProto) ProtoMessage() {}

func (x *BackingStoreProto) ProtoReflect() protoreflect.Message {
	mi := &file_frameworks_base_core_proto_android_providers_settings_generation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackingStoreProto.ProtoReflect.Descriptor instead.
func (*BackingStoreProto) Descriptor() ([]byte, []int) {
	return file_frameworks_base_core_proto_android_providers_settings_generation_proto_rawDescGZIP(), []int{1}
}

func (x *BackingStoreProto) GetKey() int32 {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return 0
}

func (x *BackingStoreProto) GetBackingStoreSize() int32 {
	if x != nil && x.BackingStoreSize != nil {
		return *x.BackingStoreSize
	}
	return 0
}

func (x *BackingStoreProto) GetNumCachedEntries() int32 {
	if x != nil && x.NumCachedEntries != nil {
		return *x.NumCachedEntries
	}
	return 0
}

func (x *BackingStoreProto) GetCacheEntries() []*CacheEntryProto {
	if x != nil {
		return x.CacheEntries
	}
	return nil
}

type CacheEntryProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Generation *int32  `protobuf:"varint,2,opt,name=generation" json:"generation,omitempty"`
}

func (x *CacheEntryProto) Reset() {
	*x = CacheEntryProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frameworks_base_core_proto_android_providers_settings_generation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheEntryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheEntryProto) ProtoMessage() {}

func (x *CacheEntryProto) ProtoReflect() protoreflect.Message {
	mi := &file_frameworks_base_core_proto_android_providers_settings_generation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheEntryProto.ProtoReflect.Descriptor instead.
func (*CacheEntryProto) Descriptor() ([]byte, []int) {
	return file_frameworks_base_core_proto_android_providers_settings_generation_proto_rawDescGZIP(), []int{2}
}

func (x *CacheEntryProto) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CacheEntryProto) GetGeneration() int32 {
	if x != nil && x.Generation != nil {
		return *x.Generation
	}
	return 0
}

var File_frameworks_base_core_proto_android_providers_settings_generation_proto protoreflect.FileDescriptor

var file_frameworks_base_core_proto_android_providers_settings_generation_proto_rawDesc = []byte{
	0x0a, 0x46, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2f, 0x62, 0x61, 0x73,
	0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6e, 0x64,
	0x72, 0x6f, 0x69, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x73,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x1a, 0x30, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x73,
	0x2f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdc, 0x01, 0x0a, 0x17, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x2c, 0x0a, 0x12, 0x6e, 0x75, 0x6d, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x69, 0x6e,
	0x67, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10,
	0x6e, 0x75, 0x6d, 0x42, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x73,
	0x12, 0x33, 0x0a, 0x16, 0x6e, 0x75, 0x6d, 0x5f, 0x6d, 0x61, 0x78, 0x5f, 0x62, 0x61, 0x63, 0x6b,
	0x69, 0x6e, 0x67, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x13, 0x6e, 0x75, 0x6d, 0x4d, 0x61, 0x78, 0x42, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x54, 0x0a, 0x0e, 0x62, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67,
	0x5f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e,
	0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x73, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x69,
	0x6e, 0x67, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x0d, 0x62, 0x61,
	0x63, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x3a, 0x08, 0x9a, 0x9f, 0xd5,
	0x87, 0x03, 0x02, 0x08, 0x64, 0x22, 0xd3, 0x01, 0x0a, 0x11, 0x42, 0x61, 0x63, 0x6b, 0x69, 0x6e,
	0x67, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2c, 0x0a,
	0x12, 0x62, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x62, 0x61, 0x63, 0x6b, 0x69,
	0x6e, 0x67, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x6e,
	0x75, 0x6d, 0x5f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x6e, 0x75, 0x6d, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x50, 0x0a, 0x0d, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x2b, 0x2e, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x0c, 0x63,
	0x61, 0x63, 0x68, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x45, 0x0a, 0x0f, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x42, 0x02, 0x50, 0x01,
}

var (
	file_frameworks_base_core_proto_android_providers_settings_generation_proto_rawDescOnce sync.Once
	file_frameworks_base_core_proto_android_providers_settings_generation_proto_rawDescData = file_frameworks_base_core_proto_android_providers_settings_generation_proto_rawDesc
)

func file_frameworks_base_core_proto_android_providers_settings_generation_proto_rawDescGZIP() []byte {
	file_frameworks_base_core_proto_android_providers_settings_generation_proto_rawDescOnce.Do(func() {
		file_frameworks_base_core_proto_android_providers_settings_generation_proto_rawDescData = protoimpl.X.CompressGZIP(file_frameworks_base_core_proto_android_providers_settings_generation_proto_rawDescData)
	})
	return file_frameworks_base_core_proto_android_providers_settings_generation_proto_rawDescData
}

var file_frameworks_base_core_proto_android_providers_settings_generation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_frameworks_base_core_proto_android_providers_settings_generation_proto_goTypes = []any{
	(*GenerationRegistryProto)(nil), // 0: android.providers.settings.GenerationRegistryProto
	(*BackingStoreProto)(nil),       // 1: android.providers.settings.BackingStoreProto
	(*CacheEntryProto)(nil),         // 2: android.providers.settings.CacheEntryProto
}
var file_frameworks_base_core_proto_android_providers_settings_generation_proto_depIdxs = []int32{
	1, // 0: android.providers.settings.GenerationRegistryProto.backing_stores:type_name -> android.providers.settings.BackingStoreProto
	2, // 1: android.providers.settings.BackingStoreProto.cache_entries:type_name -> android.providers.settings.CacheEntryProto
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_frameworks_base_core_proto_android_providers_settings_generation_proto_init() }
func file_frameworks_base_core_proto_android_providers_settings_generation_proto_init() {
	if File_frameworks_base_core_proto_android_providers_settings_generation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_frameworks_base_core_proto_android_providers_settings_generation_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GenerationRegistryProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frameworks_base_core_proto_android_providers_settings_generation_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*BackingStoreProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frameworks_base_core_proto_android_providers_settings_generation_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CacheEntryProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_frameworks_base_core_proto_android_providers_settings_generation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_frameworks_base_core_proto_android_providers_settings_generation_proto_goTypes,
		DependencyIndexes: file_frameworks_base_core_proto_android_providers_settings_generation_proto_depIdxs,
		MessageInfos:      file_frameworks_base_core_proto_android_providers_settings_generation_proto_msgTypes,
	}.Build()
	File_frameworks_base_core_proto_android_providers_settings_generation_proto = out.File
	file_frameworks_base_core_proto_android_providers_settings_generation_proto_rawDesc = nil
	file_frameworks_base_core_proto_android_providers_settings_generation_proto_goTypes = nil
	file_frameworks_base_core_proto_android_providers_settings_generation_proto_depIdxs = nil
}
